# Generated by Django 5.0.13 on 2025-07-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleekweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Description_En',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='Name_En',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Name'),
        ),
    ]
